In [ ]:
import numpy as np

In [ ]:
A = np.array([[0, 1], [2, 3], [4,5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
C = np.dot(A, B)
C

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [ ]:
C[0:4]


array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [ ]:
np.max(C)

47